[2021-07-19 20:32:16,748] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task1 2020-01-02T00:00:00+00:00 [queued]>
[2021-07-19 20:32:16,943] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task1 2020-01-02T00:00:00+00:00 [queued]>
[2021-07-19 20:32:16,953] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 20:32:16,957] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-19 20:32:16,970] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 20:32:17,087] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task1> on 2020-01-02T00:00:00+00:00
[2021-07-19 20:32:17,139] {standard_task_runner.py:52} INFO - Started process 6689 to run task
[2021-07-19 20:32:17,191] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task1', '2020-01-02T00:00:00+00:00', '--job-id', '56', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp2fei5ss3', '--error-file', '/tmp/tmpqcesr00r']
[2021-07-19 20:32:17,215] {standard_task_runner.py:77} INFO - Job 56: Subtask task1
[2021-07-19 20:32:17,889] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task1 2020-01-02T00:00:00+00:00 [running]> on host airflowvm
[2021-07-19 20:32:18,466] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2020-01-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-02T00:00:00+00:00
[2021-07-19 20:32:18,470] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-19 20:32:18,479] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-07-19 20:32:18,535] {subprocess.py:75} INFO - Output:
[2021-07-19 20:32:21,556] {subprocess.py:83} INFO - Command exited with return code 0
[2021-07-19 20:32:22,077] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task1, execution_date=20200102T000000, start_date=20210719T203216, end_date=20210719T203222
[2021-07-19 20:32:22,680] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-07-19 20:32:22,730] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-07-19 20:32:22,956] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 6689
[2021-07-19 20:32:22,998] {process_utils.py:66} INFO - Process psutil.Process(pid=6689, status='terminated', exitcode=0, started='20:32:16') (6689) terminated with exit code 0
